spring:
  application:
    name: auth-service

  # Auth Service Specific Database
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${AUTH_DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: ${AUTH_SERVICE_PORT}