spring:
  application:
    name: auth-service

  # Auth Service Specific Database
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${AUTH_DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: ${AUTH_SERVICE_PORT}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-secret-key-min-512-bits-for-hs512-algorithm-change-this-in-production}
  access-token-expiration: 3600000        # 1 hour in milliseconds
  refresh-token-expiration: 2592000000    # 30 days in milliseconds
  issuer: penny-control
  token-prefix: "Bearer "
  header-name: Authorization

# Security Configuration
security:
  public-endpoints:
    - /api/v1/auth/login
    - /api/v1/auth/register
    - /api/v1/auth/verify-email
    - /api/v1/auth/forgot-password
    - /api/v1/auth/reset-password
  allowed-origins:
    - http://localhost:3000
    - http://localhost:5173
  csrf-enabled: false