spring:
  application:
    name: user-service

  # Shared Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # Flyway Configuration (User service does NOT manage migrations)
  flyway:
    enabled: false

server:
  port: ${USER_SERVICE_PORT}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-secret-key-min-512-bits-for-hs512-algorithm-change-this-in-production}
  access-token-expiration: 3600000        # 1 hour in milliseconds
  refresh-token-expiration: 2592000000    # 30 days in milliseconds
  issuer: penny-control
  token-prefix: "Bearer "
  header-name: Authorization

# Security Configuration
security:
  public-endpoints:
    - /api/v1/users/check-username
    - /api/v1/users/check-email
  allowed-origins:
    - ${ALLOWED_ORIGIN_1:http://localhost:3000}
    - ${ALLOWED_ORIGIN_2:http://localhost:5173}