spring:
  application:
    name: user-service

  # User Service Specific Database
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${USER_DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: ${USER_SERVICE_PORT}